Added instructions on how to contribute documentation.
google/osv.dev pull request #1374
Opened 2023-06-12 03:57 UTC by hayleycd

Addresses #1372

I currently have a preview open for a different PR, but if you would like me to switch it over so you can inspect it, let me know. I have tested the documentation locally.

2023-06-12 04:59 UTC, andrewpollock requested changes
Do you want to also update https://github.com/google/osv.dev#contributing in this PR as well?

2023-06-12 04:59 UTC, andrewpollock commented on CONTRIBUTING.md
> +5. In the PR link to your fork's GitHub page, so we can preview the changes
Punctuation nit.
```suggestion
5. In the PR, link to your fork's GitHub page, so we can preview the changes
```

2023-06-12 15:23 UTC, hayleycd commented
> Do you want to also update https://github.com/google/osv.dev#contributing in this PR as well?

Thanks! Added.

2023-06-13 01:37 UTC, andrewpollock approved these changes

2023-06-13 01:38 UTC, merged