Implemented input validation for package name length
google/osv.dev pull request #1455
Opened 2023-07-10 13:15 UTC by masterismail

I've implemented the input validation for the package name length. The package name will now be checked to ensure it does not exceed the maximum allowed length of 100 characters.

Please review the changes and let me know if you have any feedback or concerns. Once the changes are merged, this issue closes #1452

2023-07-14 02:30 UTC, andrewpollock requested changes
Hello! Thanks for making this contribution, I've left some feedback.

2023-07-14 02:30 UTC, andrewpollock commented on gcp/api/server.py
> +MAX_PACKAGE_NAME_LENGTH = 100  # Maximum allowed package name length
Based on the error message cited in #1452 I think 1500 is the 

```suggestion
MAX_PACKAGE_NAME_LENGTH = 1500  # Maximum allowed package name length
```

2023-07-14 02:30 UTC, andrewpollock commented on gcp/api/server.py
> +  validate_package_name(package_name)
https://github.com/google/osv.dev/blob/6246f3be6eaaee14f6616171ef7d133c4b3cc68a/gcp/api/server.py#L445 is probably a better place to do this validation, as it is

a) earlier in the call chain
b) will also catch it for `query_by_package()`, which needs this as well

2023-08-08 00:52 UTC, andrewpollock commented
@masterismail do you plan on completing this, or should we close it out?

2023-08-08 04:49 UTC, masterismail commented
hey @andrewpollock , apologise for the delay in getting back to you. I'll be updating the code with the requested changes asap.

2023-08-08 07:06 UTC, andrewpollock commented
/gcbrun

2023-08-08 07:35 UTC, andrewpollock commented
@masterismail there's some linter errors on your change:

```
gcp/api/server.py:440:0: W0311: Bad indentation. Found 4 spaces, expected 2 (bad-indentation)
gcp/api/server.py:441:0: W0311: Bad indentation. Found 8 spaces, expected 4 (bad-indentation)
gcp/api/server.py:442:0: C0303: Trailing whitespace (trailing-whitespace)
gcp/api/server.py:794:0: C0303: Trailing whitespace (trailing-whitespace)
```

Please run https://github.com/google/osv.dev/blob/master/tools/lint_and_format.sh on your changes prior to pushing them.

2023-08-08 10:48 UTC, andrewpollock commented
@masterismail there's still some formatting errors with this change. Have you run https://github.com/google/osv.dev/blob/master/tools/lint_and_format.sh on it locally? If you run `yapf -i gcp/api/server.py` it should fix them.

2023-08-08 11:25 UTC, masterismail commented
> @masterismail there's still some formatting errors with this change. Have you run https://github.com/google/osv.dev/blob/master/tools/lint_and_format.sh on it locally? If you run `yapf -i gcp/api/server.py` it should fix them.

yes, I have run "https://github.com/google/osv.dev/blob/master/tools/lint_and_format.sh " locally, this is what I am getting


![Screenshot from 2023-08-08 16-52-25](https://github.com/google/osv.dev/assets/111173270/491dd103-8a01-4db7-89bb-feb436fb803a)

Please let me know what exactly needs to fixed

2023-08-08 21:55 UTC, andrewpollock commented
> this is what I am getting

Hi, have you set up your local development environment per https://github.com/google/osv.dev/blob/master/CONTRIBUTING.md#contributing-code?

Actually, reviewing that in conjunction with the output you've screenshotted, I can see that there's an undocumented requirement on having the Go toolchain installed. And `yapf`, which is why you didn't get locally notified about the formatting issues.

Are you as a contributor able to view https://github.com/google/osv.dev/actions/runs/5795924263/job/15708435878?pr=1455 ? That's showing the output of running `lint_and_format.sh` as part of our CI pipeline.

2023-08-09 13:55 UTC, masterismail commented
> Are you as a contributor able to view https://github.com/google/osv.dev/actions/runs/5795924263/job/15708435878?pr=1455 ? That's showing the output of running `lint_and_format.sh` as part of our CI pipeline.

yes, i'm able to see those test fails

2023-08-09 13:56 UTC, masterismail commented
> > this is what I am getting
> 
> Hi, have you set up your local development environment per https://github.com/google/osv.dev/blob/master/CONTRIBUTING.md#contributing-code?

yes, I did

2023-08-09 21:24 UTC, andrewpollock commented
> yes, I did

Yes, it turns out there were a few things necessary that weren't explicitly in the documentation, see the #1542 for what else you need to have to be able to properly check your changes locally.

2023-08-09 21:24 UTC, andrewpollock commented
> yes, i'm able to see those test fails

Cool, do you understand what you need to do to get your PR to pass, based on the failure?

2023-08-11 15:48 UTC, masterismail commented
> > yes, i'm able to see those test fails
> 
> Cool, do you understand what you need to do to get your PR to pass, based on the failure?

I don't understand why its actually failing, it rates my code 10/10

2023-08-14 04:01 UTC, andrewpollock commented
> I don't understand why its actually failing, it rates my code 10/10

`pylint` is happy with the change, `yapf` is not:

```
--- gcp/api/server.py	(original)
+++ gcp/api/server.py	(reformatted)
@@ -436,9 +436,12 @@
                                         empty_bucket_bitmap,
                                         len(version_query.file_hashes))
 
+
 def validate_package_name(package_name):
   if len(package_name) > MAX_PACKAGE_NAME_LENGTH:
     raise ValueError("Package name exceeds the maximum allowed length.")
+
+
 @ndb.tasklet
 def do_query(query, context: QueryContext, include_details=True):
   """Do a query."""
@@ -780,6 +783,7 @@
 
   return results, cursor
 
+
```

This is basically saying that you need to insert a blank line before your `validate_package_name` function and two blank lines after it (before the next function definition, `do_query`).

Take a moment to look at the formatting of the rest of the file, and you'll see that your change is inconsistent with the formatting of the file. You may also like to familiarise yourself with the [Google Python Style Guide](https://google.github.io/styleguide/pyguide.html) more broadly, for future reference.

2023-10-10 02:33 UTC, andrewpollock commented
@masterismail checking back in to see if you plan on completing this, or if we should close it?

2023-10-10 20:37 UTC, masterismail commented
I've committed the changes as requested !

2023-11-20 04:47 UTC, andrewpollock commented
/gcbrun

2023-11-20 05:52 UTC, andrewpollock commented
@masterismail it looks like there's one last lint finding to address, you're close!

2024-05-07 09:27 UTC, closed without merging