General improvements to the cloud run frontend
google/osv.dev pull request #1602
Opened 2023-08-31 04:44 UTC by another-rex

A large list of small improvements to the frontend.

- Remove highlight.js dependency since it's only used to slightly highlight the schema on the home page, but takes up 75%+ of the javascript size. 
- Pre-compress all static files and serve the compressed version, reduces traffic by 75%+
- Add max age of 1 day (vs 10 mins before in appengine) to static files to reduce the number of loads. (new updates are still pushed out immediately because of the different file names each release)
- Compress dynamic content with Flask-Compress when the response is generated
- Remove font-ligatures (the things that make `affected` look weird because `ff` becomes one character)
- Make line-height larger and consistent with blog line height in vuln description
- Improve accessibility by adding various aria-labels, 
- move font loading to the bottom of the page to prevent blocking, 
- Add meta description
- Set height and width for images

2023-08-31 04:49 UTC, another-rex commented
Original page speed analysis: https://pagespeed.web.dev/analysis/https-osv-dev/ojbx1vcw7t?form_factor=desktop
![image](https://github.com/google/osv.dev/assets/106129829/a75ceb67-54ac-4532-a07c-1848a889a0f8)

---

New page speed analysis: https://pagespeed.web.dev/analysis/https-osv-website-ivqje5d2hq-wl-a-run-app/c9f1tehq19?form_factor=desktop
![image](https://github.com/google/osv.dev/assets/106129829/5526df0a-e254-4176-8e29-2c56a7bdd33a)

2023-08-31 04:53 UTC, andrewpollock requested changes
Sick! Does any of this happen to fix the back button issues?

2023-08-31 04:53 UTC, andrewpollock commented on gcp/appengine/blog/content/posts/almalinux-and-rocky-linux-join-osv.md
> +
This looks like an errant copy pasta?

2023-08-31 04:55 UTC, another-rex commented on gcp/appengine/blog/content/posts/almalinux-and-rocky-linux-join-osv.md
> +
Ah yep, removed now.

2023-08-31 04:56 UTC, another-rex commented
> Sick! Does any of this happen to fix the back button issues?

Sadly nope, I think that's related to turbo, might not be fixable without an upstream change.

2023-08-31 05:22 UTC, michaelkedar reviewed
Nice!
Will note that the changes to compression on `/static` will only occur on the Cloud Run website mirror, since App Engine bypasses the Flask app entirely for the files in that path.

2023-08-31 05:22 UTC, michaelkedar commented on gcp/appengine/Pipfile
> +Flask-Compress = "*"
nit: pin these dependencies for consistency

2023-08-31 05:22 UTC, michaelkedar commented on gcp/appengine/Pipfile
> +whitenoise = "*"
nit: pin these dependencies for consistency

2023-08-31 05:22 UTC, michaelkedar commented on gcp/appengine/frontend3/package.json
> +    "webpack-bundle-analyzer": "^4.9.0",
nit: pin these dependencies for consistency

2023-08-31 05:22 UTC, michaelkedar commented on gcp/appengine/package-lock.json
> +{
Did you mean to create this file?

2023-08-31 05:22 UTC, michaelkedar commented on gcp/appengine/frontend3/src/templates/home.html
> +          <!-- This is built with hugo -->
Is this still being built by hugo?

2023-08-31 05:29 UTC, another-rex commented on gcp/appengine/package-lock.json
> +{
Nope, removed now.

2023-08-31 05:30 UTC, another-rex commented on gcp/appengine/frontend3/src/templates/home.html
> +          <!-- This is built with hugo -->
Nope, removed the comment

2023-09-04 23:38 UTC, andrewpollock approved these changes

2023-09-11 05:43 UTC, michaelkedar approved these changes

2023-09-19 01:09 UTC, merged