feat(osv): Add a purl converter for SwiftURL
google/osv.dev pull request #2788
Opened 2024-10-24 17:00 UTC by sschuberth

Relates to #2402.

2024-10-25 01:39 UTC, oliverchang requested changes
thanks! just a minor suggestion regarding the test

2024-10-25 01:39 UTC, oliverchang commented on osv/purl_helpers_test.py
> +                     purl_helpers.package_to_purl('SwiftURL', 'Alamofire/Alamofire'))
```suggestion
                     purl_helpers.package_to_purl('SwiftURL', 'github.com/Alamofire/Alamofire'))
```

2024-10-25 01:39 UTC, oliverchang commented on osv/purl_helpers_test.py
> +    self.assertEqual('pkg:swift/Alamofire/Alamofire',
```suggestion
    self.assertEqual('pkg:swift/github.com/Alamofire/Alamofire',
```

2024-10-25 07:36 UTC, sschuberth commented
> thanks! just a minor suggestion regarding the test

Good find, I've amended my commit.

2024-10-27 23:15 UTC, oliverchang approved these changes

2024-10-27 23:15 UTC, oliverchang commented
/gcbrun

2024-10-27 23:27 UTC, merged

2024-10-28 09:11 UTC, sschuberth commented
Thanks for the merge @oliverchang! Any idea by when it will be deployed in production?

2024-10-29 04:16 UTC, oliverchang commented
This should be released this week, but the data will require a re-import. 

@hogo6002 is this something you can help with ?

2024-10-29 04:46 UTC, hogo6002 commented
> This should be released this week, but the data will require a re-import.
> 
> @hogo6002 is this something you can help with ?

Sure, I will re-import all swiftURL records

2024-10-30 00:37 UTC, hogo6002 commented
> Sure, I will re-import all swiftURL records

It turns out that `re-putting` records is enough to add `purl`. All SwiftURLs now have `purls`: https://osv.dev/vulnerability/GHSA-q36x-r5x4-h4q6
Thanks @sschuberth  for contribution!